export const testTextValue = 'Selected value: PlumsC';
export const disableSelectModeValueTestText = 'Selected value:watermelonE';
export const selectWithTwoColumnsTestText = 'Selected Item: Lorem ipsum dolor sit, amet';
export const titleTestText = 'Title';
export const mobileExampleTestText = 'Selected: PlumsC';
export const maxHeightTestText = 'Selected value: "PlumsC"';
export const testTextValue6 = 'Selected Item: "Apple"';
export const testTextValue7 = 'Form Selected Item: { "field": "Apple" }';
export const inputStateArr = ['is-success', 'is-error', 'is-warning', 'is-information'];
