const path = require('path');
const fs = require('fs');
const yaml = require('yaml');
const WorkflowValidator = require('./workflow-validator');

const workflowPath = path.join(__dirname, '../i18n-auto-generate.yml');

// Load and parse the workflow
const content = fs.readFileSync(workflowPath, 'utf8');
const workflow = yaml.parse(content);

const validator = new WorkflowValidator(workflowPath);

// === Trigger Configuration ===
// Note: pull_request_target doesn't have 'types', it runs on the target branch
validator.assertHasPathFilter('pull_request_target', ['libs/i18n/src/lib/translations/*.properties']);

// === Job Configuration ===
validator.assertJobExists('auto_generate').assertJobEnvironment('auto_generate', 'i18n-automation');

// === Actor Guard (Prevents Duplicate Runs) ===
console.log('\n' + '='.repeat(60));
console.log('Actor Guard Check (Duplicate Run Prevention)');
console.log('='.repeat(60));

const job = workflow.jobs.auto_generate;
const jobIf = job.if;

if (!jobIf) {
    console.error('❌ ERROR: Job has no "if" condition');
    process.exit(1);
}

// Check for github.actor != 'fundamental-bot' guard
if (!jobIf.includes("github.actor != 'fundamental-bot'")) {
    console.error("❌ ERROR: Job missing guard: github.actor != 'fundamental-bot'");
    console.error('   This allows bot-triggered pushes to re-run the workflow');
    console.error('   Current condition:', jobIf);
    process.exit(1);
}

console.log("✅ Job skips execution when triggered by 'fundamental-bot'");
console.log('   Prevents duplicate runs after auto-commit');

// Check that the actor guard is combined with fork validation
if (!jobIf.includes('github.event.pull_request.head.repo.full_name')) {
    console.error('❌ ERROR: Job missing fork validation in condition');
    process.exit(1);
}

if (!jobIf.includes('service-tip-git')) {
    console.error('❌ ERROR: Job missing trusted fork owner check (service-tip-git)');
    process.exit(1);
}

console.log('✅ Job validates fork source (same-repo or service-tip-git)');

// Verify no concurrency block (which would contradict the actor guard)
if (workflow.concurrency) {
    console.warn('⚠️ WARNING: Workflow has concurrency block');
    console.warn('   With actor guard in place, concurrency is unnecessary and may mask issues');
}

// === Security: Fork validation ===
console.log('\n' + '='.repeat(60));
console.log('Fork PR Validation Logic Check');
console.log('='.repeat(60));

// Extract the validation step
const validationStep = job.steps.find((s) => s.name === 'Validate translation-only changes (fork PRs)');

if (!validationStep) {
    console.error('❌ Fork validation step not found');
    process.exit(1);
}

// Check the diff command
const stepScript = validationStep.run;
const hasTwoDot = stepScript.includes('...HEAD');
const hasCorrectDiff =
    stepScript.includes('"origin/${BASE_REF}..HEAD"') || stepScript.includes("'origin/${BASE_REF}..HEAD'");

if (hasTwoDot && !hasCorrectDiff) {
    console.error('❌ ERROR: Fork validation uses THREE-DOT diff (...)');
    console.error('   This compares against merge-base, not direct fork changes');
    console.error('   Should use TWO-DOT diff (..) for direct comparison');
    process.exit(1);
}

if (!hasCorrectDiff) {
    console.error('❌ ERROR: Fork validation diff command not found or incorrect');
    console.error('   Expected: git diff --name-only origin/${BASE_REF}..HEAD');
    process.exit(1);
}

console.log('✅ Fork validation uses correct TWO-DOT diff (..)');
console.log('   Compares fork changes directly, not against merge-base');

// Check file regex validation
const fileRegex = stepScript.match(/\^[^/]+\.properties\$/) || stepScript.match(/properties\$['"]?/);

if (!fileRegex) {
    console.error('❌ ERROR: .properties file regex not found');
    process.exit(1);
}

// The regex should ONLY allow .properties files (not .ts)
if (stepScript.includes('properties|ts')) {
    console.error('❌ ERROR: File regex allows both .properties and .ts');
    console.error('   Fork PRs should only modify .properties files');
    console.error('   .ts files are auto-generated by the workflow');
    process.exit(1);
}

console.log('✅ File validation restricts fork PRs to .properties only');
console.log('   .ts files will be auto-generated by workflow steps');

// Check that generation step exists and is after validation
const generateStep = job.steps.find((s) => s.name === 'Generate TypeScript files');
const validationStepIndex = job.steps.findIndex((s) => s.name === 'Validate translation-only changes (fork PRs)');
const generateStepIndex = job.steps.findIndex((s) => s.name === 'Generate TypeScript files');

if (!generateStep) {
    console.error('❌ ERROR: Generation step not found');
    process.exit(1);
}

if (generateStepIndex <= validationStepIndex) {
    console.error('❌ ERROR: Generation step must come AFTER validation');
    process.exit(1);
}

console.log('✅ Generation step comes after validation');
console.log('   Workflow order: validate → generate → commit');

// Check that fork push step uses GHACTIONS token
const forkPushStep = job.steps.find((s) => s.name === 'Commit and push (fork PRs)');
if (!forkPushStep) {
    console.error('❌ ERROR: Fork push step not found');
    process.exit(1);
}

if (!forkPushStep.env || !forkPushStep.env.GHACTIONS_TOKEN) {
    console.error('❌ ERROR: Fork push step missing GHACTIONS_TOKEN');
    process.exit(1);
}

console.log('✅ Fork push step properly uses GHACTIONS_TOKEN from environment');

// Check that correction commit is only for fork PRs
const correctionStep = job.steps.find((s) => s.name === 'Commit corrections (fork PRs, if auto-correct made changes)');
if (correctionStep) {
    if (
        !correctionStep.if ||
        !correctionStep.if.includes('github.event.pull_request.head.repo.full_name != github.repository')
    ) {
        console.error('❌ ERROR: Correction step must only run for fork PRs');
        process.exit(1);
    }
    console.log('✅ Auto-correction step is fork-only (prevents same-repo issues)');
}

// Summary
console.log('\n' + '='.repeat(60));
console.log('✓ All workflow validation tests passed');
console.log('='.repeat(60));

// Run structural validation
validator.report();
