// BEING UPDATED WITH THE SAP-COMPONENT SCHEMATIC; DO NOT MODIFY THE STRUCTURE!
/**
 * Files to display in the API tab of each component.
 * Names should be without hyphens, and capitalized where hyphens occur normally.
 * Include the suffix i.e. Directive or Component.
 * Names are sorted in the ApiComponent so order does not matter.
 */
export const API_FILES = {
    button: ['ButtonComponent'],
    checkbox: ['CheckboxComponent'],
    formGenerator: [
        'FormGeneratorComponent',
        'FormGeneratorService',
        'DynamicFormControlDirective',
        'DynamicFormControlFieldDirective',
        'FormGeneratorComponentsAccessorService',
        'FormGeneratorFieldComponent',
        'GetHintOptionsPipe'
    ],
    checkboxGroup: ['CheckboxGroupComponent'],
    datePicker: ['PlatformDatetimePickerComponent', 'PlatformDatePickerComponent'],
    datetimePicker: ['PlatformDatetimePickerComponent'],
    dynamicPage: [
        'DynamicPageComponent',
        'DynamicPageTitleComponent',
        'DynamicPageKeyInfoComponent',
        'DynamicPageBreadcrumbComponent',
        'DynamicPageHeaderComponent',
        'DynamicPageContentComponent',
        'DynamicPageConfig'
    ],
    formContainer: [
        'FormGroupComponent',
        'FormFieldComponent',
        'FormFieldGroupComponent',
        'FormFieldErrorDirective',
        'FormFieldErrorDescriptionDirective',
        'FormFieldErrorHeadingDirective',
        'FormGroupHeaderComponent',
        'AutoCompleteDirective',
        'CollectionBaseInput',
        'DataProvider',
        'PlatformFormFieldControl',
        'ResponsiveBreakpointsService'
    ],
    input: ['InputComponent', 'InputMessageGroupWithTemplate'],
    link: ['LinkComponent'],
    menu: ['MenuComponent', 'MenuItemComponent', 'MenuTriggerDirective'],
    menuButton: ['MenuButtonComponent'],
    objectStatus: ['ObjectStatusComponent'],
    objectMarker: ['PlatformObjectMarkerComponent'],
    radioGroup: ['RadioGroupComponent', 'RadioButtonComponent'],
    searchField: ['SearchFieldComponent'],
    select: ['SelectComponent', 'BaseSelect', 'SelectConfig'],
    splitMenuButton: ['SplitMenuButtonComponent'],
    table: [
        'TableComponent',
        'TableColumnComponent',
        'TableToolbarComponent',
        'TableToolbarActionsComponent',
        'FdpTableCell',
        'FdpCellDef',
        'FdpTableHeader',
        'FdpHeaderCellDef',
        'TableViewSettingsDialogComponent',
        'TableViewSettingsFilterComponent',
        'FdpViewSettingsFilterCustomDef',
        'TableP13DialogComponent',
        'TableP13SortComponent',
        'TableP13FilterComponent',
        'TableP13GroupComponent',
        'TableP13ColumnsComponent',
        'TableDataSource',
        'TableDataProvider',
        'ArrayTableDataProvider',
        'ChildTableDataSource',
        'FilterCustomComponent',
        'FilterMultiSelectComponent',
        'FilterRuleComponent',
        'FilterSingleSelectComponent',
        'FilterStepComponent',
        'FiltersComponent',
        'FiltersListStepComponent',
        'GroupingComponent',
        'ObservableTableDataProvider',
        'P13ColumnsDialogComponent',
        'P13FilteringDialogComponent',
        'P13GroupingDialogComponent',
        'P13SortingDialogComponent',
        'PlatformTableCellResizableDirective',
        'SortingComponent',
        'Table',
        'TableCellHeaderPopoverComponent',
        'TableChildrenDataProvider',
        'TableColumnResizeService',
        'TableDataSourceDirective',
        'TableDraggable',
        'TableDraggableDirective',
        'TableEditableCellComponent',
        'TableGroupRowComponent',
        'TableGrowingButtonComponent',
        'TableHeaderCellContentComponent',
        'TableHeaderRowComponent',
        'TableInitialState',
        'TableInitialStateDirective',
        'TablePoppingRowComponent',
        'TableResponsiveService',
        'TableRowComponent',
        'TableRowImpl',
        'TableRowService',
        'TableScrollDispatcherService',
        'TableScrollableDirective',
        'TableService',
        'TableVirtualScroll',
        'TableVirtualScrollDirective'
    ],
    textarea: ['TextAreaComponent', 'TextAreaConfig'],
    timePicker: ['PlatformTimePickerComponent'],
    panel: ['PanelComponent', 'PanelContentComponent', 'PanelActionsComponent', 'PanelConfig'],
    switch: ['SwitchComponent', 'SwitchConfig'],
    stepInput: ['NumberStepInputComponent', 'StepInputComponent', 'StepInputConfig'],
    inputGroup: ['InputGroupConfig', 'InputGroupComponent', 'InputGroupAddonComponent', 'InputGroupInputComponent'],
    combobox: ['ComboboxComponent', 'BaseCombobox', 'ComboboxConfig'],
    multiCombobox: [
        'MultiComboboxComponent',
        'BaseMultiCombobox',
        'MultiComboboxConfig',
        'MultiComboboxSelectionChangeEvent'
    ],
    list: [
        'ListComponent',
        'StandardListItemComponent',
        'ListConfig',
        'ListGroupHeaderComponent',
        'ObjectListItemRowComponent',
        'SelectionChangeEvent'
    ],
    standardlistitem: ['ListComponent', 'StandardListItemComponent', 'ListConfig'],
    actionlistitem: ['ActionListItemComponent', 'ListComponent', 'ListConfig'],
    displaylistitem: ['DisplayListItemComponent', 'ListComponent', 'ListConfig'],
    objectlistitem: ['ObjectListItemComponent', 'ListComponent', 'ListConfig'],
    multiInput: ['PlatformMultiInputComponent', 'MultiInputConfig'],
    valueHelpDialog: [
        'PlatformValueHelpDialogComponent',
        'VhdFilterComponent',
        'DefineTabComponent',
        'SelectTabComponent',
        'ValueHelpColumnDefDirective',
        'VhdBaseTab'
    ],
    feedInput: ['FeedInputComponent'],
    approvalFlow: [
        'ApprovalFlowComponent',
        'ApprovalFlowDropZoneDirective',
        'ApprovalFlowMessagesComponent',
        'ApprovalFlowNodeComponent',
        'ApprovalFlowTeamListComponent',
        'ApprovalFlowToolbarActionsComponent',
        'ApprovalFlowUserDetailsComponent',
        'ApprovalFlowUserListComponent'
    ],
    slider: ['SliderComponent'],
    footer: ['PlatformFooterComponent'],
    wizardGenerator: [
        'WizardGeneratorService',
        'WizardDialogGeneratorService',
        'WizardGeneratorComponent',
        'DialogWizardGeneratorComponent',
        'WizardBodyComponent',
        'WizardGeneratorStepComponent',
        'WizardSummaryStepComponent',
        'WizardSummarySectionComponent'
    ],
    iconTabBar: [
        'IconTabBarComponent',
        'IconTabBarTextTypeComponent',
        'IconTabBarIconTypeComponent',
        'IconTabBarProcessTypeComponent',
        'IconTabBarFilterTypeComponent',
        'IconTabBarPopoverComponent',
        'TextTypePopoverComponent',
        'IconBarDndContainerDirective',
        'IconBarDndItemDirective',
        'IconBarDndListDirective',
        'IconTabBarBase',
        'IconTabBarContentTemplateDirective',
        'IconTabBarPopoverBase',
        'IconTabBarTabComponent',
        'IconTabBarTabContentDirective',
        'IconTabBarTemplateService',
        'IconTabBarTextTypeTabItemComponent'
    ],
    smartFilterBar: [
        'SmartFilterBarComponent',
        'SmartFilterBarConditionFieldComponent',
        'SmartFilterBarConditionsDialogComponent',
        'SmartFilterBarFieldDefinitionDirective',
        'SmartFilterBarService',
        'SmartFilterBarSubjectDirective',
        'SmartFilterBarSettingsDialogComponent',
        'SmartFilterBar'
    ],
    messagePopover: [
        'MessagePopoverComponent',
        'MessagePopoverFormWrapperComponent',
        'MessageViewComponent',
        'MessagePopoverFormItemDirective'
    ],
    variantManagement: [
        'VariantManagementComponent',
        'VariantManagementWrapperComponent',
        'ManageVariantItemComponent',
        'ManageVariantsDialogComponent'
    ],
    settingsGenerator: [
        'SettingsGeneratorComponent',
        'SettingsGeneratorService',
        'SettingsGeneratorLayoutAccessorService',
        'SettingsGeneratorContentComponent',
        'SettingsGeneratorSectionComponent',
        'SettingsGeneratorSidebarLayoutComponent',
        'SettingsGeneratorSidebarIconComponent',
        'ThemeSelectorListComponent'
    ]
} as const;
