export const API_FILES = {
    actionBar: [
        'ActionBarComponent',
        'ActionBarTitleComponent',
        'ActionBarActionsDirective',
        'ActionBarBackDirective',
        'ActionBarDescriptionDirective',
        'ActionBarHeaderDirective',
        'ActionBarMobileDirective'
    ],
    actionSheet: [
        'ActionSheetComponent',
        'ActionSheetControlComponent',
        'ActionSheetItemComponent',
        'ActionSheetBodyComponent'
    ],
    alert: [],
    avatar: ['AvatarComponent'],
    avatarGroup: ['AvatarGroupComponent'],
    avatarGroupLegacy: [
        'AvatarGroupLegacyComponent',
        'AvatarGroupLegacyItemDirective',
        'AvatarGroupLegacyFocusableAvatarDirective',
        'AvatarGroupLegacyPopoverControlDirective',
        'AvatarGroupLegacyOverflowBodyDirective',
        'AvatarGroupLegacyOverflowItemDirective',
        'AvatarGroupLegacyOverflowButtonDirective',
        'AvatarGroupLegacyOverflowButtonTextDirective'
    ],
    initialFocus: ['InitialFocusDirective'],
    bar: ['BarComponent', 'BarElementDirective', 'BarLeftDirective', 'BarMiddleDirective', 'BarRightDirective'],
    card: [
        'CardComponent',
        'CardHeaderComponent',
        'CardTitleDirective',
        'CardSubtitleDirective',
        'CardSecondSubtitleDirective',
        'CardContentComponent',
        'CardLoaderComponent',
        'CardKpiHeaderComponent',
        'CardKpiValueDirective',
        'CardKpiScaleIconDirective',
        'CardKpiScaleTextDirective',
        'CardKpiAnalyticsDirective',
        'CardKpiAnalyticsLabelDirective',
        'CardKpiAnalyticsContentDirective'
    ],
    dynamicSideContent: [
        'DynamicSideContentComponent',
        'DynamicSideContentSideComponent',
        'DynamicSideContentMainComponent'
    ],
    breadcrumb: ['BreadcrumbComponent'],
    busyIndicator: ['BusyIndicatorComponent', 'BusyIndicatorExtendedDirective'],
    button: ['ButtonComponent'],
    segmentedButton: ['SegmentedButtonComponent'],
    calendar: [
        'CalendarComponent',
        'CalendarDayViewComponent',
        'CalendarMonthViewComponent',
        'CalendarYearViewComponent',
        'CalendarI18nLabels',
        'FdDate',
        'FdDatetimeAdapter'
    ],
    carousel: ['CarouselComponent', 'CarouselItemComponent', 'CarouselService'],
    combobox: ['ComboboxComponent'],
    checkbox: ['CheckboxComponent'],
    oldContentDensity: [],
    contentDensity: [
        'ContentDensityDirective',
        'ContentDensityObserver',
        'ContentDensityObserverSettings',
        'GlobalContentDensityService',
        'ContentDensityStorage',
        'ContentDensityMode'
    ],
    datePicker: ['DatePickerComponent', 'FdDate', 'FdDatetimeAdapter'],
    datetimePicker: ['DatetimePickerComponent', 'FdDate', 'FdDatetimeAdapter'],
    dynamicPage: [
        'DynamicPageComponent',
        'DynamicPageSubheaderComponent',
        'DynamicPageHeaderComponent',
        'DynamicPageTitleContentComponent',
        'DynamicPageLayoutActionsComponent',
        'DynamicPageGlobalActionsComponent',
        'DynamicPageFooterComponent',
        'DynamicPageContentComponent'
    ],
    facets: ['FacetComponent', 'FacetGroupComponent'],
    feedInput: [
        'FeedInputComponent',
        'FeedInputTextareaDirective',
        'FeedInputButtonDirective',
        'FeedInputAvatarDirective'
    ],
    feedListItem: ['FeedListComponent', 'FeedListItemComponent'],
    fileUploader: [
        'FileUploaderComponent',
        'FileUploaderSelectDirective',
        'FileUploaderDragndropDirective',
        'FileUploaderService'
    ],
    fixedCardLayout: ['FixedCardLayoutComponent', 'CardDefinitionDirective', 'FixedCardLayoutItemComponent'],
    flexibleColumnLayout: ['FlexibleColumnLayoutComponent'],
    form: [
        'FormControlComponent',
        'FormGroupComponent',
        'FormItemComponent',
        'FormLabelComponent',
        'FormHeaderComponent',
        'FormLegendDirective',
        'FormMessageComponent',
        'FormInputMessageGroupComponent'
    ],
    formattedText: ['FormattedTextComponent'],
    formMessage: ['FormInputMessageGroupComponent'],
    globalConfig: [],
    icon: ['IconComponent'],
    illustratedMessage: ['IllustratedMessageComponent'],
    infoLabel: ['InfoLabelComponent'],
    infiniteScroll: ['InfiniteScrollDirective'],
    inlineHelp: ['InlineHelpDirective'],
    inputGroup: ['InputGroupComponent'],
    layoutGrid: ['LayoutGridComponent', 'LayoutGridColDirective', 'LayoutGridRowDirective'],
    layoutPanel: [
        'LayoutPanelComponent',
        'LayoutPanelActionsComponent',
        'LayoutPanelBodyComponent',
        'LayoutPanelDescriptionComponent',
        'LayoutPanelFiltersComponent',
        'LayoutPanelFooterComponent',
        'LayoutPanelHeaderComponent',
        'LayoutPanelHeadComponent',
        'LayoutPanelTitleDirective'
    ],
    link: ['LinkComponent'],
    list: [
        'ListComponent',
        'ListTitleDirective',
        'ListSecondaryDirective',
        'ListGroupHeaderDirective',
        'ListIconDirective',
        'ListFooterDirective',
        'ListMessageDirective',
        'ListNavigationItemArrowDirective',
        'ListNavigationItemTextDirective',
        'ListNavigationItemComponent',
        'ListSublineDirective',
        'ListInfoLabelDirective'
    ],
    menu: ['MenuAddonDirective', 'MenuComponent', 'MenuTitleDirective', 'MenuKeyboardService'],
    messageStrip: [
        'MessageStripComponent',
        'AutoDismissMessageStripDirective',
        'MessageStripAlertService',
        'MessageStripAlertRef'
    ],
    messageToast: ['MessageToastComponent', 'MessageToastConfig', 'MessageToastService', 'MessageToastRef'],
    microProcessFlow: ['MicroProcessFlowComponent', 'MicroProcessFlowItemComponent', 'MicroProcessFlowIconComponent'],
    momentDatetimeAdapter: [],
    dayjsDatetimeAdapter: [],
    dialog: [
        'DialogService',
        'DialogContainerComponent',
        'DialogTitleDirective',
        'DialogConfig',
        'DialogPosition',
        'DialogBodyComponent',
        'DialogHeaderComponent',
        'DialogFooterComponent',
        'DialogRef'
    ],
    multiInput: ['MultiInputComponent'],
    messageBox: [
        'MessageBoxRef',
        'MessageBoxConfig',
        'MessageBoxContent',
        'MessageBoxService',
        'MessageBoxComponent',
        'MessageBoxBodyComponent',
        'MessageBoxHeaderComponent',
        'MessageBoxFooterComponent',
        'MessageBoxDefaultComponent',
        'MessageBoxSemanticIconComponent',
        'MessageBoxContainerComponent'
    ],
    notification: [
        'NotificationTitleDirective',
        'NotificationParagraphDirective',
        'NotificationFooterContentDirective',
        'NotificationSeparatorDirective',
        'NotificationActionsComponent',
        'NotificationContentComponent',
        'NotificationGroupHeaderComponent',
        'NotificationGroupComponent',
        'NotificationGroupListComponent',
        'NotificationComponent',
        'NotificationHeaderComponent',
        'NotificationBodyComponent',
        'NotificationFooterComponent',
        'NotificationContainer',
        'NotificationConfig',
        'NotificationRef'
    ],
    objectAttribute: ['ObjectAttributeComponent'],
    objectIdentifier: ['ObjectIdentifierComponent'],
    objectMarker: ['ObjectMarkerComponent'],
    objectStatus: ['ObjectStatusModule', 'ObjectStatusComponent'],
    pagination: ['PaginationComponent', 'PaginationService'],
    panel: ['PanelComponent', 'PanelTitleDirective'],
    popover: [
        'PopoverComponent',
        'PopoverBodyComponent',
        'PopoverControlComponent',
        'PopoverBodyHeaderDirective',
        'PopoverBodyFooterDirective'
    ],
    objectNumber: ['ObjectNumberComponent'],
    productSwitch: ['ProductSwitchComponent', 'ProductSwitchItem'],
    progressIndicator: ['ProgressIndicatorComponent'],
    quickView: [
        'QuickViewComponent',
        'QuickViewTitleComponent',
        'QuickViewSubheaderComponent',
        'QuickViewSubheaderTitleComponent',
        'QuickViewSubheaderSubtitleComponent',
        'QuickViewGroupComponent',
        'QuickViewGroupTitleComponent',
        'QuickViewGroupItemComponent',
        'QuickViewGroupItemLabelComponent',
        'QuickViewGroupItemContentComponent',
        'QuickViewGroupItemContentElementDirective'
    ],
    scrollSpy: ['ScrollSpyDirective'],
    select: ['SelectComponent', 'OptionComponent'],
    shellbar: [
        'ProductMenuComponent',
        'ShellbarComponent',
        'ShellbarActionComponent',
        'ShellbarActionsComponent',
        'ShellbarLogoComponent',
        'ShellbarSubtitleComponent',
        'ShellbarTitleComponent',
        'ShellbarBrandingComponent',
        'ShellbarContextAreaComponent'
    ],
    sideNavigation: [
        'SideNavigationComponent',
        'SideNavigationModel',
        'SideNavigationUtilityDirective',
        'NestedListDirective',
        'NestedListPopoverComponent',
        'NestedListHeaderDirective',
        'NestedListIconComponent',
        'NestedListItem',
        'NestedListModel',
        'NestedListLink',
        'NestedItemService'
    ],
    splitButton: ['SplitButtonComponent', 'SplitButtonActionTitle'],
    table: [
        'TableBodyDirective',
        'TableCellDirective',
        'TableHeaderDirective',
        'TableRowDirective',
        'TableComponent',
        'TableResponsiveWrapperDirective',
        'TableWrapperComponent',
        'TableFixedDirective'
    ],
    tabs: [
        'TabListComponent',
        'TabPanelComponent',
        'TabTitleDirective',
        'TabNavComponent',
        'TabLinkDirective',
        'TabItemDirective',
        'TabTagDirective',
        'TabIconComponent',
        'TabCountDirective',
        'TabLabelDirective',
        'TabProcessDirective',
        'TabHeaderDirective',
        'TabCounterHeaderDirective',
        'TabProcessIconDirective',
        'TabItemExpandComponent'
    ],
    text: ['TextComponent'],
    tile: [
        'TileComponent',
        'TileHeaderDirective',
        'TileContentDirective',
        'TileFooterDirective',
        'TileTitleDirective',
        'TileSubtitleDirective',
        'TileSectionDirective',
        'TileRefreshDirective',
        'TileFooterTextDirective',
        'TileHeaderContentDirective',
        'TileProfileImgDirective',
        'TileLogoDirective',
        'TileContentTextDirective',
        'TileBackgroundImgDirective',
        'TileToggleDirective',
        'TileContainerDirective',
        'TilePageIndicatorDirective',
        'TileActionCloseDirective',
        'TileActionIndicatorDirective',
        'TileTitleContainerDirective',
        'TileActionContainerDirective',
        'NumericContentDirective',
        'NumericContentKpiContainerDirective',
        'NumericContentKpiDirective',
        'NumericContentLaunchIconContainerDirective',
        'NumericContentLaunchIconDirective',
        'NumericContentScaleArrowDirective',
        'NumericContentScaleContainerDirective',
        'NumericContentScaleDirective',
        'NumericContentScaleTextDirective'
    ],
    time: ['TimeComponent', 'TimeColumnComponent'],
    timePicker: ['TimePickerComponent', 'FdDate', 'FdDatetimeAdapter'],
    title: ['TitleComponent'],
    truncate: ['TruncateDirective'],
    switch: ['SwitchComponent'],
    stepInput: ['StepInputComponent'],
    slider: ['SliderComponent'],
    token: ['TokenComponent', 'TokenizerComponent'],
    toolbar: ['ToolbarComponent'],
    tree: ['TreeComponent', 'TreeItemComponent', 'TreeItemDefDirective'],
    ratingIndicator: ['RatingIndicatorComponent'],
    wizard: ['WizardComponent'],
    gridList: [
        'GridListComponent',
        'GridListItemComponent',
        'GridListTitleBarComponent',
        'GridListFilterBarComponent',
        'GridListMoreBtnComponent',
        'GridListFooterComponent',
        'GridListItemFooterBarComponent',
        'GridListItemToolbarComponent',
        'GridListGroupHeaderComponent'
    ],
    statusIndicator: ['StatusIndicatorComponent'],
    messagePage: [
        'MessagePageComponent',
        'MessagePageActionsComponent',
        'MessagePageMoreComponent',
        'MessagePageTitleComponent',
        'MessagePageSubtitleComponent'
    ],
    resizableCardLayout: ['ResizableCardLayoutComponent', 'ResizableCardItemComponent'],
    verticalNavigation: [
        'VerticalNavigationComponent',
        'VerticalNavigationMainNavigationComponent',
        'VerticalNavigationGroupHeaderDirective'
    ],
    uploadCollection: [
        'UploadCollectionComponent',
        'UploadCollectionButtonGroupComponent',
        'UploadCollectionFormItemComponent',
        'UploadCollectionItemDirective',
        'UploadCollectionThumbnailDirective',
        'UploadCollectionTitleDirective',
        'UploadCollectionDescriptionDirective',
        'UploadCollectionTextSeparatorDirective',
        'UploadCollectionStatusGroupDirective',
        'UploadCollectionTitleContainerDirective'
    ],
    timeline: [
        'TimelineComponent',
        'TimelineNodeDefDirective',
        'TimelineNodeBodyComponent',
        'TimelineNodeComponent',
        'TimelineNodeHeaderInfoTitleDirective',
        'TimelineNodeHeaderInfoTextDirective',
        'TimelineHeaderInfoSubTitleDirective'
    ],
    scrollbar: [],
    theming: ['ThemingService', 'BaseThemingConfig'],
    overflowLayout: [
        'OverflowLayoutComponent',
        'OverflowItemRefDirective',
        'OverflowExpandDirective',
        'OverflowLayoutItemDirective',
        'OverflowItemContainerRefDirective',
        'OverflowLayoutPopoverContentDirective'
    ],
    skeleton: ['SkeletonComponent'],
    multiCombobox: [
        'MultiComboboxComponent',
        'MobileMultiComboboxComponent',
        'MultiComboboxSelectionChangeEvent',
        'MultiComboboxDataSourceParser',
        'FdMultiComboBoxDataSource'
    ],
    genericTag: ['GenericTagComponent'],
    settingsDialog: [
        'SettingsComponent',
        'SettingsContainerComponent',
        'SettingsContentDirective',
        'SettingsDetailAreaDirective',
        'SettingsDialogBodyDirective',
        'SettingsDialogContentDirective',
        'SettingsHeaderDirective',
        'SettingsHeaderButtonDirective',
        'SettingsListAreaDirective',
        'SettingsListContainerDirective'
    ],
    userMenu: ['UserMenuComponent']
};
