// BEING UPDATED WITH THE SAP-COMPONENT SCHEMATIC; DO NOT MODIFY THE STRUCTURE!

/**
 * Files to display in the API tab of each component.
 * Names should be without hyphens, and capitalized where hyphens occur normally.
 * Include the suffix i.e. Directive or Component.
 * Names are sorted in the ApiComponent so order does not matter.
 */
export const API_FILES = {
    actionBar: [
        'ActionBarComponent',
        'ActionBarTitleComponent',
        'ActionBarActionsDirective',
        'ActionBarBackDirective',
        'ActionBarDescriptionDirective',
        'ActionBarHeaderDirective',
        'ActionBarMobileDirective'
    ],
    actionSheet: [
        'ActionSheetComponent',
        'ActionSheetControlComponent',
        'ActionSheetItemComponent',
        'ActionSheetBodyComponent'
    ],
    alert: [],
    avatar: ['AvatarComponent', 'AvatarIconPipe'],
    avatarGroup: [
        'AvatarGroupComponent',
        'AvatarGroupItemDirective',
        'AvatarGroupOverflowBodyComponent',
        'AvatarGroupOverflowButtonComponent'
    ],
    avatarGroupLegacy: [
        'AvatarGroupLegacyComponent',
        'AvatarGroupLegacyItemDirective',
        'AvatarGroupLegacyFocusableAvatarDirective',
        'AvatarGroupLegacyPopoverControlDirective',
        'AvatarGroupLegacyOverflowBodyDirective',
        'AvatarGroupLegacyOverflowItemDirective',
        'AvatarGroupLegacyOverflowButtonDirective',
        'AvatarGroupLegacyOverflowButtonTextDirective'
    ],
    initialFocus: ['InitialFocusDirective'],
    bar: [
        'BarComponent',
        'BarElementDirective',
        'BarLeftDirective',
        'BarMiddleDirective',
        'BarRightDirective',
        'ButtonBarComponent'
    ],
    card: [
        'CardComponent',
        'CardHeaderComponent',
        'CardTitleDirective',
        'CardSubtitleDirective',
        'CardSecondSubtitleDirective',
        'CardContentComponent',
        'CardLoaderComponent',
        'CardKpiHeaderComponent',
        'CardKpiValueDirective',
        'CardKpiScaleIconDirective',
        'CardKpiScaleTextDirective',
        'CardKpiAnalyticsDirective',
        'CardKpiAnalyticsLabelDirective',
        'CardKpiAnalyticsContentDirective',
        'CardCounterDirective',
        'CardExtendedHeaderComponent',
        'CardHeaderColumnDirective',
        'CardListDirective',
        'CardMainHeaderComponent',
        'CardMediaComponent',
        'CardMediaContentContainerDirective',
        'CardMediaHeadingDirective',
        'CardNumericHeaderComponent'
    ],
    dynamicSideContent: [
        'DynamicSideContentComponent',
        'DynamicSideContentSideComponent',
        'DynamicSideContentMainComponent'
    ],
    breadcrumb: ['BreadcrumbComponent', 'BreadcrumbItemComponent'],
    busyIndicator: ['BusyIndicatorComponent', 'BusyIndicatorExtendedDirective'],
    button: ['ButtonComponent', 'ButtonBadgeDirective'],
    segmentedButton: ['SegmentedButtonComponent'],
    calendar: [
        'CalendarComponent',
        'CalendarDayViewComponent',
        'CalendarMonthViewComponent',
        'CalendarYearViewComponent',
        'CalendarI18nLabels',
        'FdDate',
        'FdDatetimeAdapter',
        'CalendarAggregatedYearViewComponent',
        'CalendarHeaderComponent',
        'CalendarLegendComponent',
        'CalendarLegendFocusingService',
        'CalendarService'
    ],
    carousel: [
        'CarouselComponent',
        'CarouselItemComponent',
        'CarouselService',
        'CarouselDirective',
        'CarouselItemDirective'
    ],
    combobox: ['ComboboxComponent', 'ListGroupPipe'],
    checkbox: ['CheckboxComponent'],
    oldContentDensity: [],
    contentDensity: [
        'ContentDensityDirective',
        'ContentDensityObserver',
        'ContentDensityObserverSettings',
        'GlobalContentDensityService',
        'ContentDensityStorage',
        'ContentDensityMode'
    ],
    datePicker: [
        'DatePickerComponent',
        'FdDate',
        'FdDatetimeAdapter',
        'DatetimeAdapter',
        'DateFormatPipe',
        'DateFromNowPipe',
        'DateTimeFormatPipe',
        'DayPeriodFormatPipe',
        'TranslateDayPeriodPipe'
    ],
    datetimePicker: ['DatetimePickerComponent', 'FdDate', 'FdDatetimeAdapter'],
    dynamicPage: [
        'DynamicPageComponent',
        'DynamicPageSubheaderComponent',
        'DynamicPageHeaderComponent',
        'DynamicPageTitleContentComponent',
        'DynamicPageLayoutActionsComponent',
        'DynamicPageGlobalActionsComponent',
        'DynamicPageFooterComponent',
        'DynamicPageContentComponent',
        'DynamicPageBaseActions'
    ],
    facets: ['FacetComponent', 'FacetGroupComponent', 'FacetContainerComponent'],
    feedInput: [
        'FeedInputComponent',
        'FeedInputTextareaDirective',
        'FeedInputButtonDirective',
        'FeedInputAvatarDirective'
    ],
    feedListItem: ['FeedListComponent', 'FeedListItemComponent'],
    fileUploader: [
        'FileUploaderComponent',
        'FileUploaderSelectDirective',
        'FileUploaderDragndropDirective',
        'FileUploaderService'
    ],
    fixedCardLayout: ['FixedCardLayoutComponent', 'CardDefinitionDirective', 'FixedCardLayoutItemComponent'],
    flexibleColumnLayout: ['FlexibleColumnLayoutComponent'],
    form: [
        'FormControlComponent',
        'FormGroupComponent',
        'FormItemComponent',
        'FormLabelComponent',
        'FormHeaderComponent',
        'FormLegendDirective',
        'FormMessageComponent',
        'FormInputMessageGroupComponent',
        'PopoverFormMessageService'
    ],
    formattedText: ['FormattedTextComponent'],
    formMessage: ['FormInputMessageGroupComponent'],
    globalConfig: [],
    icon: ['IconComponent'],
    illustratedMessage: ['IllustratedMessageComponent'],
    infoLabel: ['InfoLabelComponent'],
    infiniteScroll: ['InfiniteScrollDirective'],
    inlineHelp: ['InlineHelpDirective'],
    inputGroup: ['InputGroupComponent', 'InputGroupAddOnDirective', 'InputGroupInputDirective'],
    layoutGrid: ['LayoutGridComponent', 'LayoutGridColDirective', 'LayoutGridRowDirective'],
    layoutPanel: [
        'LayoutPanelComponent',
        'LayoutPanelActionsComponent',
        'LayoutPanelBodyComponent',
        'LayoutPanelDescriptionComponent',
        'LayoutPanelFiltersComponent',
        'LayoutPanelFooterComponent',
        'LayoutPanelHeaderComponent',
        'LayoutPanelHeadComponent',
        'LayoutPanelTitleDirective'
    ],
    link: ['LinkComponent'],
    list: [
        'ListComponent',
        'ListTitleDirective',
        'ListSecondaryDirective',
        'ListGroupHeaderDirective',
        'ListIconDirective',
        'ListFooterDirective',
        'ListMessageDirective',
        'ListNavigationItemArrowDirective',
        'ListNavigationItemTextDirective',
        'ListNavigationItemComponent',
        'ListSublineDirective',
        'ListInfoLabelDirective',
        'ListBylineDirective',
        'ListBylineLeftDirective',
        'ListBylineRightDirective',
        'ListFocusItem',
        'ListItemComponent'
    ],
    menu: [
        'MenuAddonDirective',
        'MenuComponent',
        'MenuTitleDirective',
        'MenuKeyboardService',
        'DefaultMenuItem',
        'MenuItemComponent',
        'MenuItemInputDirective',
        'MenuMobileComponent',
        'MenuService',
        'MenuShortcutDirective',
        'MenuSubtitleDirective',
        'SubmenuComponent',
        'ToggleButtonDirective'
    ],
    messageStrip: [
        'MessageStripComponent',
        'AutoDismissMessageStripDirective',
        'MessageStripAlertService',
        'MessageStripAlertRef'
    ],
    messageToast: [
        'MessageToastComponent',
        'MessageToastConfig',
        'MessageToastService',
        'MessageToastRef',
        'ToastOverlayContainer'
    ],
    microProcessFlow: [
        'MicroProcessFlowComponent',
        'MicroProcessFlowItemComponent',
        'MicroProcessFlowIconComponent',
        'MicroProcessFlowFocusableItemDirective'
    ],
    datetimeAdapters: [
        'FdDatetimeAdapter',
        'DayjsDatetimeAdapter',
        'MomentDatetimeAdapter',
        'DatetimeAdapter',
        'DateTimeFormats'
    ],
    dialog: [
        'DialogService',
        'DialogContainerComponent',
        'DialogTitleDirective',
        'DialogConfig',
        'DialogPosition',
        'DialogBodyComponent',
        'DialogHeaderComponent',
        'DialogFooterComponent',
        'DialogRef',
        'DialogBaseService',
        'DialogCloseButtonComponent',
        'DialogDefaultComponent',
        'DialogFullScreenTogglerButtonComponent',
        'DialogOverlayContainer',
        'DialogRefBase',
        'DialogTemplateDirective'
    ],
    multiInput: ['MultiInputComponent', 'MultiInputMobileComponent'],
    messageBox: [
        'MessageBoxRef',
        'MessageBoxConfig',
        'MessageBoxContent',
        'MessageBoxService',
        'MessageBoxComponent',
        'MessageBoxBodyComponent',
        'MessageBoxHeaderComponent',
        'MessageBoxFooterComponent',
        'MessageBoxDefaultComponent',
        'MessageBoxSemanticIconComponent',
        'MessageBoxContainerComponent',
        'MessageBoxTemplateDirective'
    ],
    notification: [
        'NotificationTitleDirective',
        'NotificationParagraphDirective',
        'NotificationFooterContentDirective',
        'NotificationSeparatorDirective',
        'NotificationActionsComponent',
        'NotificationContentComponent',
        'NotificationGroupHeaderComponent',
        'NotificationGroupComponent',
        'NotificationGroupListComponent',
        'NotificationComponent',
        'NotificationHeaderComponent',
        'NotificationBodyComponent',
        'NotificationFooterComponent',
        'NotificationContainer',
        'NotificationConfig',
        'NotificationRef',
        'NotificationGroupHeaderTitleDirective',
        'NotificationLinkComponent',
        'NotificationListDirective',
        'NotificationService'
    ],
    objectAttribute: ['ObjectAttributeComponent'],
    objectIdentifier: ['ObjectIdentifierComponent'],
    objectMarker: ['ObjectMarkerComponent'],
    objectStatus: ['ObjectStatusComponent'],
    pagination: ['PaginationComponent', 'PaginationService'],
    panel: ['PanelComponent', 'PanelTitleDirective', 'PanelContentDirective'],
    popover: [
        'PopoverComponent',
        'PopoverBodyComponent',
        'PopoverControlComponent',
        'PopoverBodyHeaderDirective',
        'PopoverBodyFooterDirective',
        'PopoverMobileComponent',
        'PopoverPosition',
        'PopoverService'
    ],
    objectNumber: ['ObjectNumberComponent'],
    productSwitch: ['ProductSwitchComponent', 'ProductSwitchItem', 'ProductSwitchBodyComponent'],
    progressIndicator: ['ProgressIndicatorComponent'],
    quickView: [
        'QuickViewComponent',
        'QuickViewTitleComponent',
        'QuickViewSubheaderComponent',
        'QuickViewSubheaderTitleComponent',
        'QuickViewSubheaderSubtitleComponent',
        'QuickViewGroupComponent',
        'QuickViewGroupTitleComponent',
        'QuickViewGroupItemComponent',
        'QuickViewGroupItemLabelComponent',
        'QuickViewGroupItemContentComponent',
        'QuickViewGroupItemContentElementDirective'
    ],
    scrollSpy: ['ScrollSpyDirective'],
    select: [
        'SelectComponent',
        'OptionComponent',
        'SelectableItemDirective',
        'SelectableItemToken',
        'SelectionService'
    ],
    shellbar: [
        'ProductMenuComponent',
        'ShellbarComponent',
        'ShellbarActionComponent',
        'ShellbarActionsComponent',
        'ShellbarLogoComponent',
        'ShellbarSubtitleComponent',
        'ShellbarTitleComponent',
        'ShellbarBrandingComponent',
        'ShellbarContextAreaComponent',
        'ShellbarActionsMobileComponent',
        'ShellbarUserMenuButtonDirective',
        'ShellbarUserMenuComponent'
    ],
    radio: ['RadioButtonComponent'],
    sideNavigation: [
        'SideNavigationComponent',
        'SideNavigationModel',
        'SideNavigationUtilityDirective',
        'NestedListDirective',
        'NestedListPopoverComponent',
        'NestedListHeaderDirective',
        'NestedListIconComponent',
        'NestedListItem',
        'NestedListModel',
        'NestedListLink',
        'NestedItemService',
        'NestedItemDirective',
        'NestedLinkDirective',
        'NestedListContentDirective',
        'NestedListExpandIconComponent',
        'NestedListKeyboardService',
        'NestedListTitleDirective',
        'PreparedNestedListComponent'
    ],
    splitButton: ['SplitButtonComponent', 'SplitButtonActionTitle'],
    table: [
        'TableBodyDirective',
        'TableCellDirective',
        'TableHeaderDirective',
        'TableRowDirective',
        'TableComponent',
        'TableResponsiveWrapperDirective',
        'TableWrapperComponent',
        'TableFixedDirective',
        'TableContainerDirective',
        'TableIconDirective',
        'TableStatusIndicatorDirective',
        'TableTextDirective'
    ],
    tabs: [
        'TabListComponent',
        'TabPanelComponent',
        'TabTitleDirective',
        'TabNavComponent',
        'TabLinkDirective',
        'TabItemDirective',
        'TabTagDirective',
        'TabIconComponent',
        'TabCountDirective',
        'TabLabelDirective',
        'TabProcessDirective',
        'TabHeaderDirective',
        'TabCounterHeaderDirective',
        'TabProcessIconDirective',
        'TabItemExpandComponent'
    ],
    text: ['TextComponent'],
    tile: [
        'TileComponent',
        'TileHeaderDirective',
        'TileContentDirective',
        'TileFooterDirective',
        'TileTitleDirective',
        'TileSubtitleDirective',
        'TileSectionDirective',
        'TileRefreshDirective',
        'TileFooterTextDirective',
        'TileHeaderContentDirective',
        'TileProfileImgDirective',
        'TileLogoDirective',
        'TileContentTextDirective',
        'TileBackgroundImgDirective',
        'TileToggleDirective',
        'TileContainerDirective',
        'TilePageIndicatorDirective',
        'TileActionCloseDirective',
        'TileActionIndicatorDirective',
        'TileTitleContainerDirective',
        'TileActionContainerDirective',
        'NumericContentDirective',
        'NumericContentKpiContainerDirective',
        'NumericContentKpiDirective',
        'NumericContentLaunchIconContainerDirective',
        'NumericContentLaunchIconDirective',
        'NumericContentScaleArrowDirective',
        'NumericContentScaleContainerDirective',
        'NumericContentScaleDirective',
        'NumericContentScaleTextDirective'
    ],
    time: ['TimeComponent', 'TimeColumnComponent'],
    timePicker: ['TimePickerComponent', 'FdDate', 'FdDatetimeAdapter'],
    title: ['TitleComponent'],
    truncate: ['TruncateDirective', 'TruncatePipe'],
    switch: ['SwitchComponent'],
    stepInput: ['StepInputComponent'],
    slider: ['SliderComponent', 'SliderPositionDirective'],
    token: ['TokenComponent', 'TokenizerComponent', 'TokenizerInputDirective'],
    toolbar: ['ToolbarComponent', 'ToolbarItemDirective', 'ToolbarSpacerDirective'],
    tree: ['TreeComponent', 'TreeItemComponent', 'TreeItemDefDirective', 'TreeDataSourceParser', 'TreeItemDirective'],
    ratingIndicator: ['RatingIndicatorComponent', 'RatingStarLabelPipe'],
    wizard: [
        'WizardComponent',
        'WizardContentComponent',
        'WizardNextStepComponent',
        'WizardProgressBarDirective',
        'WizardStepComponent',
        'WizardStepIndicatorComponent'
    ],
    gridList: [
        'GridListComponent',
        'GridListItemComponent',
        'GridListTitleBarComponent',
        'GridListFilterBarComponent',
        'GridListMoreBtnComponent',
        'GridListFooterComponent',
        'GridListItemFooterBarComponent',
        'GridListItemToolbarComponent',
        'GridListGroupHeaderComponent'
    ],
    statusIndicator: ['StatusIndicatorComponent'],
    messagePage: [
        'MessagePageComponent',
        'MessagePageActionsComponent',
        'MessagePageMoreComponent',
        'MessagePageTitleComponent',
        'MessagePageSubtitleComponent'
    ],
    resizableCardLayout: ['ResizableCardLayoutComponent', 'ResizableCardItemComponent', 'ResizedEvent'],
    verticalNavigation: [
        'VerticalNavigationComponent',
        'VerticalNavigationMainNavigationComponent',
        'VerticalNavigationGroupHeaderDirective'
    ],
    uploadCollection: [
        'UploadCollectionComponent',
        'UploadCollectionButtonGroupComponent',
        'UploadCollectionFormItemComponent',
        'UploadCollectionItemDirective',
        'UploadCollectionThumbnailDirective',
        'UploadCollectionTitleDirective',
        'UploadCollectionDescriptionDirective',
        'UploadCollectionTextSeparatorDirective',
        'UploadCollectionStatusGroupDirective',
        'UploadCollectionTitleContainerDirective'
    ],
    timeline: [
        'TimelineComponent',
        'TimelineNodeDefDirective',
        'TimelineNodeBodyComponent',
        'TimelineNodeComponent',
        'TimelineNodeHeaderInfoTitleDirective',
        'TimelineNodeHeaderInfoTextDirective',
        'TimelineHeaderInfoSubTitleDirective',
        'HorizontalDoubleSidesStrategy',
        'HorizontalSingleSideStrategy',
        'PositionStrategyFactory',
        'TimelinePositionControlService',
        'VerticalDoubleSidesStrategy',
        'VerticalSingleSideStrategy'
    ],
    scrollbar: ['ScrollbarDirective'],
    theming: ['ThemingService', 'BaseThemingConfig'],
    overflowLayout: [
        'OverflowLayoutComponent',
        'OverflowItemRefDirective',
        'OverflowExpandDirective',
        'OverflowLayoutItemDirective',
        'OverflowItemContainerRefDirective',
        'OverflowLayoutPopoverContentDirective',
        'OverflowLayoutFocusableItemDirective',
        'OverflowLayoutService'
    ],
    skeleton: ['SkeletonComponent'],
    multiCombobox: [
        'MultiComboboxComponent',
        'MobileMultiComboboxComponent',
        'MultiComboboxSelectionChangeEvent',
        'MultiComboboxDataSourceParser',
        'FdMultiComboBoxDataSource',
        'SelectAllTogglerComponent'
    ],
    genericTag: ['GenericTagComponent'],
    settingsDialog: [
        'SettingsComponent',
        'SettingsContainerComponent',
        'SettingsContentDirective',
        'SettingsDetailAreaDirective',
        'SettingsDialogBodyDirective',
        'SettingsDialogContentDirective',
        'SettingsHeaderDirective',
        'SettingsHeaderButtonDirective',
        'SettingsListAreaDirective',
        'SettingsListContainerDirective'
    ],
    userMenu: [
        'UserMenuComponent',
        'UserMenuBodyComponent',
        'UserMenuControlComponent',
        'UserMenuListItemComponent',
        'UserMenuSublineDirective',
        'UserMenuSublistComponent',
        'UserMenuUserNameDirective'
    ]
} as const;
