/**
 * Created by i856224 on 8/13/18.
 */

export const AribaIcons = [

  { key:'workspace', code:'\eA01'},
  { key:'auction', code:'\eA02'},
  { key:'table-angle', code:'\eA03'},
  { key:'rfi-doc', code:'\eA04'},
  { key:'rfp-doc', code:'\eA05'},
  { key:'info', code:'\eA06'},
  { key:'table-customization', code:'\eA07'},
  { key:'rfx-doc', code:'\eA08'},
  { key:'share', code:'\eA09'},
  { key:'expand', code:'\eA0A'},
  { key:'collapse', code:'\eA0B'},
  { key:'function', code:'\eA0C'},
  { key:'divide', code:'\eA0d'},
  { key:'left-bracket', code:'\eA0e'},
  { key:'right-bracket', code:'\eA0f'},

  { key:'empty', code:'\eA10'},
  { key:'grade', code:'\eA11'},
  { key:'ms-project-doc', code:'\eA12'},
  { key:'knowledge-project', code:'\eA13'},
  { key:'notification1', code:'\eA14'},
  { key:'contract', code:'\eA15'},
  { key:'separator', code:'\eA16'},
  { key:'template', code:'\eA17'},
  { key:'notification2t', code:'\eA18'},
  { key:'live', code:'\eA19'},
  { key:'rtl-table-angle', code:'\eA1a'},
  { key:'rtl-in-progress', code:'\eA1b'},
  { key:'rtl-pending', code:'\eA1c'},
  { key:'rtl-child', code:'\eA1d'},
  { key:'rtl-expand', code:'\eA1e'},


  { key:'pin', code:'\eA20'},
  { key:'ariba', code:'\eA21'},
  { key:'sort-up', code:'\eA22'},
  { key:'sort-down', code:'\eA23'},
  { key:'pull-down', code:'\eA24'},
  { key:'share-thin', code:'\eA25'},
  { key:'home', code:'\eA26'},
  { key:'analytics', code:'\eA27'},
  { key:'reporting', code:'\eA28'},
  { key:'notusing', code:'\eA29'},


  { key:'pinned', code:'\eA30'},
  { key:'hedge-oil', code:'\eA31'},
  { key:'more', code:'\eA32'},
  { key:'open-panel', code:'\eA33'},
  { key:'add-non-catalog-item', code:'\eA34'},
  { key:'adashboard', code:'\eA35'},
  { key:'ms-in-progress', code:'\eA36'},
  { key:'ms-complete', code:'\eA37'},
  { key:'ms-cancel', code:'\eA38'},
  { key:'ms-denied', code:'\eA39'},


  { key:'cancelled', code:'\eA40'},
  { key:'in-progress', code:'\eA41'},
  { key:'pending', code:'\eA42'},
  { key:'grab', code:'\eA43'},
  { key:'lightening', code:'\eA44'},
  { key:'under-construction', code:'\eA45'},
  { key:'bid', code:'\eA46'},
  { key:'best-bid', code:'\eA47'},
  { key:'gate', code:'\eA48'},
  { key:'gate-action', code:'\eA49'},


  { key:'invoice-reconcile', code:'\eA50'},
  { key:'purchase-order', code:'\eA51'},
  { key:'kit', code:'\eA52'},
  { key:'punch-out', code:'\eA53'},
  { key:'currency', code:'\eA54'},
  { key:'gold', code:'\eA55'},
  { key:'platinum', code:'\eA56'},
  { key:'silver', code:'\eA57'},
  { key:'hazard', code:'\eA58'},
  { key:'invoice', code:'\eA59'},


  { key:'accounting-expand', code:'\eA60'},
  { key:'revalidate', code:'\eA61'},
  { key:'measure', code:'\eA62'},
  { key:'summary', code:'\eA63'},
  { key:'disable', code:'\eA64'},
  { key:'saved-cart', code:'\eA65'},
  { key:'new', code:'\eA66'},
  { key:'add-message', code:'\eA67'},
  { key:'message-composed', code:'\eA68'},
  { key:'message-sent', code:'\eA69'},


  { key:'incumbent', code:'\eA70'},
  { key:'WS-contract', code:'\eA71'},
  { key:'WS-dform', code:'\eA72'},
  { key:'WS-personal', code:'\eA73'},
  { key:'WS-supplier-management', code:'\eA74'},
  { key:'WS-resourcing', code:'\eA75'},
  { key:'WS-supplier-performance-mngt', code:'\eA76'},
  { key:'WS-knowledge-proj', code:'\eA77'},
  { key:'women-owned', code:'\eA78'},
  { key:'catalog', code:'\eA79'},


  { key:'non-catalog-item', code:'\eA80'},
  { key:'pull-up', code:'\eA81'},
  { key:'add-comment', code:'\eA82'},
  { key:'edit-comment', code:'\eA83'},
  { key:'child', code:'\eA84'},
  { key:'surrogate', code:'\eA85'},
  { key:'commodity-map', code:'\eA86'},
  { key:'cif-uom', code:'\eA87'},
  { key:'toggle-off', code:'\eA88'},
  { key:'toggle-no', code:'\eA89'},


  { key:'half-star', code:'\eA90'},
  { key:'rfq-doc', code:'\eA91'},
  { key:'inquiry', code:'\eA92'},
  { key:'document-vsd', code:'\eA93'},
  { key:'document-mpp', code:'\eA94'},
  { key:'service-sheet', code:'\eA95'},
  { key:'ship-notice', code:'\eA96'},
  { key:'close-panel', code:'\eA97'},
  { key:'like', code:'\eA98'},
  { key:'customer-service', code:'\eA99'},
  { key:'penalty', code:'\eA9a'},
  { key:'flag2', code:'\eA9b'},
  { key:'warning', code:'\eA9c'},
  { key:'error', code:'\eA9d'},


  { key:'add-template', code:'\eB01'},
  { key:'end-point', code:'\eB02'},
  { key:'file-converter', code:'\eB03'},
  { key:'file', code:'\eB04'},
  { key:'filter', code:'\eB05'},
  { key:'joiner', code:'\eB06'},
  { key:'mapper', code:'\eB07'},
  { key:'publisher', code:'\eB08'},
  { key:'refresh', code:'\eB09'},


  { key:'search', code:'\eB10'},
  { key:'settings', code:'\eB11'},
  { key:'share-social', code:'\eB12'},
  { key:'trash', code:'\eB13'},
  { key:'close', code:'\eB14'},
  { key:'start', code:'\eB15'},
  { key:'arrow-down', code:'\eB16'},
  { key:'automap', code:'\eB17'},
  { key:'portfolio', code:'\eB18'},
  { key:'discovery', code:'\eB19'},


  { key:'home2', code:'\eB20'},
  { key:'learn', code:'\eB21'},
  { key:'admin', code:'\eB22'},
  { key:'menu', code:'\eB23'},
  { key:'register', code:'\eB24'},
  { key:'facebook', code:'\eB25'},
  { key:'twitter', code:'\eB26'},
  { key:'google-plus', code:'\eB27'},
  { key:'youtube', code:'\eB28'},
  { key:'linkedin', code:'\eB29'},


  { key:'discussion', code:'\eB30'},
  { key:'minus', code:'\eB31'},
  { key:'forms', code:'\eB32'},
  { key:'flows', code:'\eB33'},
  { key:'dashboard', code:'\eB34'},
  { key:'apps', code:'\eB35'},
  { key:'rtl-start', code:'\eB36'},

];
