name: Bug Report
description: Report a bug.
labels: ['bug']
body:
    - type: markdown
      attributes:
          value: |
              **IMPORTANT:** Please refrain from providing any internal or sensitive information like: internal urls, login credentials, screenshots of applications or features in development, as this project is open-source, and its contents are accessible to anyone.

    - type: textarea
      id: proposal-description
      attributes:
          label: Describe your proposal
          description: Please provide a detailed description of your proposal, bug.
      validations:
          required: true

    - type: input
      id: versions
      attributes:
          label: Which versions of Angular and Fundamental Library for Angular are affected?
          description: Specify the exact versions. (If requesting a feature, use current version.)
          placeholder: 'Angular: x.y.z, Fundamental Library: x.y.z, UI5 Web Components: x.y.z'
      validations:
          required: true

    - type: input
      id: component
      attributes:
          label: Affected Component
      validations:
          required: false

    - type: textarea
      id: reproduction-steps
      attributes:
          label: Steps to Reproduce (for bugs)
          description: Provide steps for reproducing the issue, including the exact components you are using.
          placeholder: |
              1. Go to ...
              2. Click on ...
              3. ...
      validations:
          required: false

    - type: input
      id: stackblitz
      attributes:
          label: StackBlitz example(s)
          description: If possible, provide a link to a minimal reproducible saved StackBlitz.
          placeholder: 'https://stackblitz.com/...'
      validations:
          required: false

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: |
              The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
              - Breaks entire application or system - High or Very High
              - Accessibility issue - Medium or High
              - Functional issue - Medium or High
              - Visual issue - Low or Medium
          multiple: false
          options:
              - Low
              - Medium
              - High
              - Very High
      validations:
          required: false

    - type: markdown
      attributes:
          value: |
              ## Privacy Policy
              Please don't disclose any internal or sensitive information like: internal urls, login credentials, screenshots of applications or features in development.
              This is a public GitHub repository and all the information is publicly available.

    - type: checkboxes
      id: confirmation
      attributes:
          label: Declaration
          description: By submitting this issue, I confirm to follow the recommendation not to disclose any internal or sensitive information.
          options:
              - label: I'm not disclosing any internal or sensitive information.
                required: true
