name: Action for semantic version bump
description: Bump version of root package.json

inputs:
    isPrerelease:
        description: Whether this is a prerelease
        required: false
        default: 'false'
    isHotfix:
        description: Whether this is a hotfix
        required: false
        default: 'false'
    isManual:
        description: Whether this was triggered manually (by a commit message)
        required: false
        default: 'false'
outputs:
    newVersion:
        description: New version
    isPrerelease:
        description: Is prerelease version
    releaseTag:
        description: Release tag

runs:
    using: node16
    main: ./index.js
