import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, relative, resolve } from 'path';
import { discoverExamples, ExampleMetadata } from './utils/discover-examples';

const WORKSPACE_ROOT = resolve(__dirname, '../../..');
const GENERATED_ROUTES_PATH = resolve(__dirname, '../src/app/app.routes.generated.ts');
const ROUTES_JSON_PATH = resolve(__dirname, '../e2e/config/e2e.routes.json');
const SKIP_LIST_PATH = resolve(__dirname, '../e2e/config/e2e.skip.json');

function loadSkipList(): Set<string> {
    try {
        const raw = readFileSync(SKIP_LIST_PATH, 'utf-8');
        const data = JSON.parse(raw) as { skipped: { route: string }[] };
        return new Set(data.skipped.map((s) => s.route));
    } catch {
        return new Set();
    }
}

function buildRoutesFile(examples: ExampleMetadata[]): string {
    const routesDir = dirname(GENERATED_ROUTES_PATH);

    const imports = examples.map((ex) => {
        const importPath = relative(routesDir, resolve(WORKSPACE_ROOT, ex.filePath)).replace(/\.ts$/, '');
        // Ensure unix-style path separators
        const normalizedPath = importPath.split('\\').join('/');
        return `    {\n        path: '${ex.routePath}',\n        loadComponent: () =>\n            import('${normalizedPath}').then(m => m.${ex.className})\n    }`;
    });

    return `// AUTO-GENERATED by generate-routes.ts — DO NOT EDIT
/* eslint-disable @nx/enforce-module-boundaries */
import { Routes } from '@angular/router';

export const generatedRoutes: Routes = [
${imports.join(',\n')}
];
`;
}

function buildRoutesJson(examples: ExampleMetadata[]): object {
    return {
        generated: new Date().toISOString(),
        count: examples.length,
        routes: examples.map((ex) => ({
            path: ex.routePath,
            library: ex.library,
            component: ex.component,
            example: ex.exampleName,
            className: ex.className
        }))
    };
}

function main(): void {
    console.log('Discovering example components...');
    const allExamples = discoverExamples(WORKSPACE_ROOT);
    console.log(`Found ${allExamples.length} example components.`);

    const skipList = loadSkipList();
    const examples = allExamples.filter((ex) => !skipList.has(ex.routePath));
    if (skipList.size > 0) {
        console.log(`Skipped ${allExamples.length - examples.length} routes (see e2e.skip.json).`);
    }

    // Write generated routes TS file
    const routesContent = buildRoutesFile(examples);
    writeFileSync(GENERATED_ROUTES_PATH, routesContent, 'utf-8');
    console.log(`Written: ${GENERATED_ROUTES_PATH}`);

    // Write routes JSON manifest for tests
    mkdirSync(dirname(ROUTES_JSON_PATH), { recursive: true });
    const routesJson = buildRoutesJson(examples);
    writeFileSync(ROUTES_JSON_PATH, JSON.stringify(routesJson, null, 2) + '\n', 'utf-8');
    console.log(`Written: ${ROUTES_JSON_PATH}`);

    // Summary per library
    const byLibrary = new Map<string, number>();
    for (const ex of examples) {
        byLibrary.set(ex.library, (byLibrary.get(ex.library) || 0) + 1);
    }
    console.log('\nBreakdown by library:');
    for (const [lib, count] of [...byLibrary.entries()].sort()) {
        console.log(`  ${lib}: ${count}`);
    }
}

main();
