name: NX cloud runner
description: Spins up nx cloud runner

inputs:
    agent-name:
        description: 'Name of the agent'
        required: true
        default: 'agent'

runs:
    using: composite
    steps:
        - uses: actions/checkout@v3
        - uses: ./.github/actions/nodejs
          with:
              node-version: 14.20.0
        - run: |
              export DISPLAY=:99
              sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          shell: bash
        - name: Start Nx Agent ${{inputs.agent}}
          run: npx nx-cloud start-agent
          shell: bash
          env:
              NX_AGENT_NAME: ${{inputs.agent}}
              name: Nx Cloud Agents
