import { workspaceRoot } from '@nx/devkit';
import { readFileSync, writeFileSync } from 'fs';
import { CommentType } from '../schema';
import { generateComment } from '../utils/comment-generator';
import { updateFdLanguageInterface } from '../utils/interface-updater';
import { addKeyToProperties, keyExists } from '../utils/properties-parser';
import { regenerateTypeScriptFiles } from './sync';

export interface AddKeyOptions {
    key: string;
    value: string;
    comment?: string;
    commentType?: CommentType;
    propertiesPath: string;
}

export interface AddKeyResult {
    success: boolean;
    filesModified: string[];
    error?: string;
}

/**
 * Validate key format (must be component.keyName)
 */
function validateKeyFormat(key: string): { valid: boolean; error?: string } {
    if (!key || key.trim() === '') {
        return { valid: false, error: 'Key cannot be empty' };
    }

    const parts = key.split('.');
    if (parts.length < 2) {
        return {
            valid: false,
            error: `Invalid key format: "${key}". Expected format: "component.keyName" (e.g., "coreButton.save")`
        };
    }

    // Check for valid characters (alphanumeric, underscore, dot)
    if (!/^[a-zA-Z0-9_.]+$/.test(key)) {
        return {
            valid: false,
            error: `Invalid characters in key: "${key}". Only alphanumeric, underscore, and dots are allowed`
        };
    }

    return { valid: true };
}

/**
 * Add a new translation key to all TypeScript translation files
 */
export async function addKey(options: AddKeyOptions): Promise<AddKeyResult> {
    const { key, value, comment, commentType, propertiesPath } = options;

    // Step 1: Validate key format
    const validation = validateKeyFormat(key);
    if (!validation.valid) {
        return {
            success: false,
            filesModified: [],
            error: validation.error
        };
    }

    // Step 1.5: Validate that comment is provided (unless commentType is NOTR)
    // Note: comment is optional; if not provided, it will be auto-generated by generateComment()
    if (!comment && commentType === 'NOTR') {
        // NOTR type explicitly requires no comment
    }

    // Step 2: Read the base translations.properties file to check if key exists
    const basePropertiesFile = `${workspaceRoot}/${propertiesPath}/translations.properties`;
    try {
        const baseContent = readFileSync(basePropertiesFile, 'utf-8');
        if (keyExists(baseContent, key)) {
            return {
                success: false,
                filesModified: [],
                error: `Key "${key}" already exists in translations.properties. Use update command to modify existing keys.`
            };
        }
    } catch (error) {
        return {
            success: false,
            filesModified: [],
            error: `Failed to read translations.properties: ${error instanceof Error ? error.message : String(error)}`
        };
    }

    // Step 2.5: Validate key format (reject multi-dot keys)
    const keyParts = key.split('.');
    if (keyParts.length > 2) {
        return {
            success: false,
            filesModified: [],
            error: `Invalid key format: "${key}". Keys must be in format "component.keyName" with a single dot. Multi-level keys like "component.sub.key" are not supported.`
        };
    }

    // Step 3: Add key to base translations.properties file (write properties first for safer atomicity)
    try {
        const baseContent = readFileSync(basePropertiesFile, 'utf-8');
        const commentInfo = generateComment(key, value, comment, commentType);
        const updatedContent = addKeyToProperties(baseContent, {
            key,
            value,
            commentType: commentInfo.type,
            commentDescription: commentInfo.description
        });
        writeFileSync(basePropertiesFile, updatedContent, 'utf-8');
    } catch (error) {
        return {
            success: false,
            filesModified: [],
            error: `Failed to add key to translations.properties: ${error instanceof Error ? error.message : String(error)}`
        };
    }

    // Step 3.5: Update fd-language.ts interface with the new key (after properties succeeds).
    // Trade-off: if this write fails, properties is already updated but interface is stale.
    // Recovery: run `sync` — it regenerates TypeScript from properties, making it the source of truth.
    const fdLanguagePath = `${workspaceRoot}/libs/i18n/src/lib/models/fd-language.ts`;
    try {
        const fdLanguageContent = readFileSync(fdLanguagePath, 'utf-8');
        const [componentName, keyName] = keyParts;
        const commentInfo = generateComment(key, value, comment, commentType);

        const updatedFdLanguage = updateFdLanguageInterface(
            fdLanguageContent,
            componentName,
            keyName,
            commentInfo.type,
            commentInfo.description
        );

        // Only write if content changed
        if (updatedFdLanguage !== fdLanguageContent) {
            writeFileSync(fdLanguagePath, updatedFdLanguage, 'utf-8');
        }
    } catch (error) {
        return {
            success: false,
            filesModified: [],
            error: `Failed to update fd-language.ts: ${error instanceof Error ? error.message : String(error)}`
        };
    }

    // Step 4: Regenerate all TypeScript files from .properties files
    const result = await regenerateTypeScriptFiles(propertiesPath);
    if (!result.success) {
        return result;
    }

    // Step 5: Verify the comment was written to the file
    try {
        const updatedContent = readFileSync(basePropertiesFile, 'utf-8');
        const keyRegex = new RegExp(`#([A-Z]{4}):\\s*[^\\n]*\\n\\s*${key.replace(/\./g, '\\.')}\\s*=`, 'm');
        if (!keyRegex.test(updatedContent)) {
            return {
                success: false,
                filesModified: [],
                error: `Failed to verify comment for key "${key}". The key was added but the SAP UI5 comment may not have been written correctly. Please run: nx run i18n:i18n-manage --command=validate`
            };
        }
    } catch (error) {
        return {
            success: false,
            filesModified: [],
            error: `Failed to verify comment was written: ${error instanceof Error ? error.message : String(error)}`
        };
    }

    // Include the base properties file and fd-language.ts in the modified files list
    return {
        success: true,
        filesModified: [
            `${propertiesPath}/translations.properties`,
            'libs/i18n/src/lib/models/fd-language.ts',
            ...result.filesModified
        ]
    };
}
