name: Update version on main

inputs:
    name:
        description: Github user name
        required: true
    email:
        description: Github email
        required: true
    token:
        description: GH Token
        required: true

runs:
    using: composite
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
              ref: main
              fetch-depth: 0
              token: ${{ inputs.token }}

        - name: Setup Node.js and Cache
          uses: ./.github/actions/nodejs

        - name: Bump Version
          id: bumpVersion
          uses: ./.github/actions/bump-version
          with:
              isPrerelease: false
              writeFile: true

        - name: Update Changelog
          run: npx conventional-changelog-cli -p angular -i CHANGELOG.md -s
          shell: bash

        - uses: ./.github/actions/set-up-git
          name: Set up git user
          with:
              name: ${{ inputs.name }}
              email: ${{ inputs.email }}

        - name: Commit Changes
          run: |
              git add .
              git commit -m "chore(release): release v${{ steps.bumpVersion.outputs.newVersion }} [ci skip]" --no-verify
              git push
          shell: bash
