import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SkeletonModule } from '@fundamental-ngx/core/skeleton';

import { TileComponent } from './tile.component';
import {
    TileContentDirective,
    TileHeaderDirective,
    TileFooterDirective,
    TileSectionDirective,
    TileSubtitleDirective,
    TileTitleDirective,
    TileRefreshDirective,
    TileFooterTextDirective,
    TileHeaderContentDirective,
    TileProfileImgDirective,
    TileLogoDirective,
    TileContentBylineDirective,
    TileContentTextDirective,
    TileBackgroundImgDirective,
    TileToggleDirective,
    TileContainerDirective,
    TilePageIndicatorDirective,
    TileDotDirective,
    TileActionCloseDirective,
    TileActionIndicatorDirective,
    TileTitleContainerDirective,
    TileActionContainerDirective,
    TileSlideContainerDirective
} from './directives/tile.directives';
import {
    NumericContentDirective,
    NumericContentKpiContainerDirective,
    NumericContentKpiDirective,
    NumericContentLaunchIconContainerDirective,
    NumericContentLaunchIconDirective,
    NumericContentScaleArrowDirective,
    NumericContentScaleContainerDirective,
    NumericContentScaleDirective,
    NumericContentScaleTextDirective
} from './directives/numeric-content.directives';

@NgModule({
    imports: [CommonModule, SkeletonModule],
    exports: [
        TileComponent,
        TileHeaderDirective,
        TileContentDirective,
        TileFooterDirective,
        TileTitleDirective,
        TileSubtitleDirective,
        TileSectionDirective,
        TileRefreshDirective,
        TileFooterTextDirective,
        TileHeaderContentDirective,
        TileProfileImgDirective,
        TileLogoDirective,
        TileContentBylineDirective,
        TileContentTextDirective,
        TileBackgroundImgDirective,
        TileToggleDirective,
        TileContainerDirective,
        TilePageIndicatorDirective,
        TileDotDirective,
        TileActionCloseDirective,
        TileActionIndicatorDirective,
        TileTitleContainerDirective,
        TileActionContainerDirective,
        TileSlideContainerDirective,
        NumericContentDirective,
        NumericContentKpiContainerDirective,
        NumericContentKpiDirective,
        NumericContentLaunchIconContainerDirective,
        NumericContentLaunchIconDirective,
        NumericContentScaleArrowDirective,
        NumericContentScaleContainerDirective,
        NumericContentScaleDirective,
        NumericContentScaleTextDirective
    ],
    declarations: [
        TileComponent,
        TileHeaderDirective,
        TileContentDirective,
        TileFooterDirective,
        TileTitleDirective,
        TileSubtitleDirective,
        TileSectionDirective,
        TileRefreshDirective,
        TileFooterTextDirective,
        TileHeaderContentDirective,
        TileProfileImgDirective,
        TileLogoDirective,
        TileContentBylineDirective,
        TileContentTextDirective,
        TileBackgroundImgDirective,
        TileToggleDirective,
        TileContainerDirective,
        TilePageIndicatorDirective,
        TileDotDirective,
        TileActionCloseDirective,
        TileActionIndicatorDirective,
        TileTitleContainerDirective,
        TileActionContainerDirective,
        TileSlideContainerDirective,
        NumericContentDirective,
        NumericContentScaleArrowDirective,
        NumericContentKpiContainerDirective,
        NumericContentKpiDirective,
        NumericContentLaunchIconContainerDirective,
        NumericContentLaunchIconDirective,
        NumericContentScaleContainerDirective,
        NumericContentScaleDirective,
        NumericContentScaleTextDirective
    ]
})
export class TileModule {}
