name: Fundamental-ngx action for Node.js
description: Node.js setup cache

inputs:
    node-version:
        description: Node.js version
        required: false
        default: 22.x
    frozen-lockfile:
        description: Install dependencies from lock file
        required: false
        default: 'true'

runs:
    using: composite
    steps:
        - name: Use Node.js ${{ inputs.node-version }}
          uses: actions/setup-node@v4.3.0
          with:
              node-version: ${{ inputs.node-version }}

        - name: Get Yarn path from .yarnrc.yml
          id: yarn-path
          shell: bash
          run: |
              YARN_PATH=$(grep '^yarnPath:' .yarnrc.yml | awk '{print $2}')
              echo "path=$YARN_PATH" >> $GITHUB_OUTPUT
              echo "Using Yarn at: $YARN_PATH"

        - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "dir=$(node ${{ steps.yarn-path.outputs.path }} config get cacheFolder)" >> $GITHUB_OUTPUT
          shell: bash

        # Optimized cache strategy: Use Yarn cache only (not node_modules)
        # This prevents cache thrashing and ensures consistent builds
        - name: Cache Yarn dependencies
          uses: actions/cache@v4.2.3
          with:
              path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
              key: ${{ runner.os }}-yarn-${{ inputs.node-version }}-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                  ${{ runner.os }}-yarn-${{ inputs.node-version }}-
                  ${{ runner.os }}-yarn-

        - name: Install dependencies
          run: node ${{ steps.yarn-path.outputs.path }} install ${{ inputs.frozen-lockfile == 'true' && '--frozen-lockfile' || '' }}
          shell: bash

        - name: Output nx build logs
          if: failure()
          run: |
              log_files=$(find /tmp -name '*.log')
              echo "Found log files: $log_files"

              for log_file in $log_files; do
                echo "====== Contents of $log_file ======"
                cat "$log_file"
              done
          shell: bash
