export * from './avatar-group.component';
export * from './avatar-group.module';
export * from './components/avatar-group-overflow-body/avatar-group-overflow-body.component';
export * from './components/avatar-group-overflow-button.component';
export * from './directives/avatar-group-item.directive';
export * from './directives/avatar-group-overflow-body.directive';
export * from './directives/avatar-group-overflow-button.directive';
export * from './tokens';
export * from './types';
