name: Set up git user
description: Action for setting up git user
inputs:
    name:
        description: Github user name
        required: true
    email:
        description: Github email
        required: true

runs:
    using: composite
    steps:
        - name: Set up git user
          run: |
              git config --global user.email "${{ inputs.email }}"
              git config --global user.name "${{ inputs.name }}"
          shell: bash
