import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
    selector: 'fdp-list-with-infinite-scroll-example',
    templateUrl: './platform-list-with-infinite-scroll-example.component.html',
    styles: [
        `.example-viewport {
            height: 200px;
            width: 100%;
          }
        `
    ],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlatformListWithInfiniteScrollExampleComponent {

    displayedElements = [
        { 'title': 'Alabama', 'secondary': 'Montgomery' },
        { 'title': 'Alaska', 'secondary': 'Juneau' },
        { 'title': 'Arizona', 'secondary': 'Phoenix' },
        { 'title': 'Arkansas', 'secondary': 'Little Rock' },
        { 'title': 'California', 'secondary': 'Sacramento' },
        { 'title': 'Colorado', 'secondary': 'Denver' },
        { 'title': 'Connecticut', 'secondary': 'Hartford' },
        { 'title': 'Delaware', 'secondary': 'Dover' },
        { 'title': 'Florida', 'secondary': 'Tallahassee' },
        { 'title': 'Georgia', 'secondary': 'Atlanta' },
        { 'title': 'Hawaii', 'secondary': 'Honolulu' },
        { 'title': 'Idaho', 'secondary': 'Boise' },
        { 'title': 'Illinois', 'secondary': 'Springfield' },
        { 'title': 'Indiana', 'secondary': 'Indianapolis' },
        { 'title': 'Iowa', 'secondary': 'Des Moines' },
        { 'title': 'Kansas', 'secondary': 'Topeka' },
        { 'title': 'Kentucky', 'secondary': 'Frankfort' },
        { 'title': 'Louisiana', 'secondary': 'Baton Rouge' },
        { 'title': 'Maine', 'secondary': 'Augusta' },
        { 'title': 'Maryland', 'secondary': 'Annapolis' },
        { 'title': 'Massachusetts', 'secondary': 'Boston' },
        { 'title': 'Michigan', 'secondary': 'Lansing' },
        { 'title': 'Minnesota', 'secondary': 'St. Paul' },
        { 'title': 'Mississippi', 'secondary': 'Jackson' },
        { 'title': 'Missouri', 'secondary': 'Jefferson City' },
        { 'title': 'Montana', 'secondary': 'Helena' },
        { 'title': 'Nebraska', 'secondary': 'Lincoln' },
        { 'title': 'Nevada', 'secondary': 'Carson City' },
        { 'title': 'New Hampshire', 'secondary': 'Concord' },
        { 'title': 'New Jersey', 'secondary': 'Trenton' },
        { 'title': 'New Mexico', 'secondary': 'Santa Fe' },
        { 'title': 'New York', 'secondary': 'Albany' },
        { 'title': 'North Carolina', 'secondary': 'Raleigh' },
        { 'title': 'North Dakota', 'secondary': 'Bismarck' },
        { 'title': 'Ohio', 'secondary': 'Columbus' },
        { 'title': 'Oklahoma', 'secondary': 'Oklahoma City' },
        { 'title': 'Oregon', 'secondary': 'Salem' },
        { 'title': 'Pennsylvania', 'secondary': 'Harrisburg' },
        { 'title': 'Rhode Island', 'secondary': 'Providence' },
        { 'title': 'South Carolina', 'secondary': 'Columbia' },
        { 'title': 'South Dakota', 'secondary': 'Pierre' },
        { 'title': 'Tennessee', 'secondary': 'Nashville' },
        { 'title': 'Texas', 'secondary': 'Austin' },
        { 'title': 'Utah', 'secondary': 'Salt Lake City' },
        { 'title': 'Vermont', 'secondary': 'Montpelier' },
        { 'title': 'Virginia', 'secondary': 'Richmond' },
        { 'title': 'Washington', 'secondary': 'Olympia' },
        { 'title': 'West Virginia', 'secondary': 'Charleston' },
        { 'title': 'Wisconsin', 'secondary': 'Madison' },
        { 'title': 'Wyoming', 'secondary': 'Cheyenne' },
        { 'title': 'Alaska', 'secondary': 'Juneau' },
        { 'title': 'Arizona', 'secondary': 'Phoenix' },
        { 'title': 'Arkansas', 'secondary': 'Little Rock' },
        { 'title': 'California', 'secondary': 'Sacramento' },
        { 'title': 'Colorado', 'secondary': 'Denver' },
        { 'title': 'Connecticut', 'secondary': 'Hartford' },
        { 'title': 'Delaware', 'secondary': 'Dover' },
        { 'title': 'Florida', 'secondary': 'Tallahassee' },
        { 'title': 'Georgia', 'secondary': 'Atlanta' },
        { 'title': 'Hawaii', 'secondary': 'Honolulu' },
        { 'title': 'Idaho', 'secondary': 'Boise' },
        { 'title': 'Illinois', 'secondary': 'Springfield' },
        { 'title': 'Indiana', 'secondary': 'Indianapolis' },
        { 'title': 'Iowa', 'secondary': 'Des Moines' },
        { 'title': 'Kansas', 'secondary': 'Topeka' },
        { 'title': 'Kentucky', 'secondary': 'Frankfort' },
        { 'title': 'Louisiana', 'secondary': 'Baton Rouge' },
        { 'title': 'Maine', 'secondary': 'Augusta' },
        { 'title': 'Maryland', 'secondary': 'Annapolis' },
        { 'title': 'Massachusetts', 'secondary': 'Boston' },
        { 'title': 'Michigan', 'secondary': 'Lansing' },
        { 'title': 'Minnesota', 'secondary': 'St. Paul' },
        { 'title': 'Mississippi', 'secondary': 'Jackson' },
        { 'title': 'Missouri', 'secondary': 'Jefferson City' },
        { 'title': 'Montana', 'secondary': 'Helena' },
        { 'title': 'Nebraska', 'secondary': 'Lincoln' },
        { 'title': 'Nevada', 'secondary': 'Carson City' },
        { 'title': 'New Hampshire', 'secondary': 'Concord' },
        { 'title': 'New Jersey', 'secondary': 'Trenton' },
        { 'title': 'New Mexico', 'secondary': 'Santa Fe' },
        { 'title': 'New York', 'secondary': 'Albany' },
        { 'title': 'North Carolina', 'secondary': 'Raleigh' },
        { 'title': 'North Dakota', 'secondary': 'Bismarck' },
        { 'title': 'Ohio', 'secondary': 'Columbus' },
        { 'title': 'Oklahoma', 'secondary': 'Oklahoma City' },
        { 'title': 'Oregon', 'secondary': 'Salem' },
        { 'title': 'Pennsylvania', 'secondary': 'Harrisburg' },
        { 'title': 'Rhode Island', 'secondary': 'Providence' },
        { 'title': 'South Carolina', 'secondary': 'Columbia' },
        { 'title': 'South Dakota', 'secondary': 'Pierre' },
        { 'title': 'Tennessee', 'secondary': 'Nashville' },
        { 'title': 'Texas', 'secondary': 'Austin' },
        { 'title': 'Utah', 'secondary': 'Salt Lake City' },
        { 'title': 'Vermont', 'secondary': 'Montpelier' },
        { 'title': 'Virginia', 'secondary': 'Richmond' },
        { 'title': 'Washington', 'secondary': 'Olympia' },
        { 'title': 'West Virginia', 'secondary': 'Charleston' },
        { 'title': 'Wisconsin', 'secondary': 'Madison' },
        { 'title': 'Wyoming', 'secondary': 'Cheyenne' }
    ];
}
