export interface AddressCSV {
  UniqueName: string;
  Name: string;
  Lines: string;
  City: string;
  State: string;
  PostalCode: any;
  Country: string;
  Phone: string;
  Fax: string;
  Email: string;
  URL: string;
}


export const addressDB: Array<AddressCSV> = [
  {
    UniqueName: 'US001',
    Name: 'Austin',
    Lines: '3450 Industrial Park Road',
    City: 'Austin',
    State: 'TX',
    PostalCode: 78701,
    Country: 'US',
    Phone: '214-401-5555',
    Fax: '214-401-5575',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US002',
    Name: 'Sacramento Mfg.',
    Lines: '1000 Global Parkway',
    City: 'Sacramento',
    State: 'CA',
    PostalCode: 95801,
    Country: 'US',
    Phone: '916-465-7810',
    Fax: '916-465-7819',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US003',
    Name: 'Sacramento',
    Lines: '1400 Global Parkway',
    City: 'Sacramento',
    State: 'CA',
    PostalCode: 95801,
    Country: 'US',
    Phone: '916-465-7890',
    Fax: '916-465-7699',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US004',
    Name: 'Sacramento Sales',
    Lines: '1200 Global Parkway',
    City: 'Sacramento',
    State: 'CA',
    PostalCode: 95801,
    Country: 'US',
    Phone: '916-451-6325',
    Fax: '916-451-6330',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US005',
    Name: 'CA Hqtrs.',
    Lines: '3000 Airport Boulevard',
    City: 'San Francisco',
    State: 'CA',
    PostalCode: 94128,
    Country: 'US',
    Phone: '65-338-8484',
    Fax: '65-338-7777',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US006',
    Name: 'New York Sales',
    Lines: '4500 8th Avenue',
    City: 'New York',
    State: 'NY',
    PostalCode: 10037,
    Country: 'US',
    Phone: '212-415-6000',
    Fax: '212-415-6140',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US007',
    Name: 'New York R&D',
    Lines: '8000 Hudson Avenue',
    City: 'White Plains',
    State: 'NY',
    PostalCode: 10687,
    Country: 'US',
    Phone: '212-451-6010',
    Fax: '212-451-6050',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US008',
    Name: 'San Francisco Dist',
    Lines: '3000 Airport Boulevard',
    City: 'San Francisco',
    State: 'CA',
    PostalCode: 94128,
    Country: 'US',
    Phone: '415-356-5500',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US009',
    Name: 'New York Dist.',
    Lines: '4500 Constitution Boulevard',
    City: 'New York',
    State: 'NY',
    PostalCode: 10037,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US010',
    Name: 'Headquarters',
    Lines: '1450 Global Parkway',
    City: 'Sacramento',
    State: 'CA',
    PostalCode: 95802,
    Country: 'US',
    Phone: '916-465-7890',
    Fax: '916-465-7699',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'DEFAULT_BILLING_ADDRESS',
    Name: 'Headquarters',
    Lines: '1450 Global Parkway',
    City: 'Sacramento',
    State: 'CA',
    PostalCode: 95802,
    Country: 'US',
    Phone: '916-465-7890',
    Fax: '916-465-7699',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US011',
    Name: 'Ariba Headquarters',
    Lines: '1314 Chesapeake Terrace',
    City: 'Sunnyvale',
    State: 'CA',
    PostalCode: 94089,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US012',
    Name: 'Ariba Headquarters',
    Lines: '1314 Chesapeake Terrace',
    City: 'Sunnyvale',
    State: 'CA',
    PostalCode: 94089,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US013',
    Name: 'California',
    Lines: '123 North Main Street',
    City: 'San Francisco',
    State: 'CA',
    PostalCode: 94100,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US014',
    Name: 'Oklahoma City',
    Lines: '50 Second St.',
    City: 'Oklahoma City',
    State: 'OK',
    PostalCode: 73132,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US015',
    Name: 'Los Gatos',
    Lines: '15 Camino del Cerro',
    City: 'Los Gatos',
    State: 'CA',
    PostalCode: 95032,
    Country: 'US',
    Phone: '408/358-2000',
    Fax: '408/358-2100',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US016',
    Name: 'Gilroy',
    Lines: '727 Christopher Ranch Road Garlic Capital of the World',
    City: 'Gilroy',
    State: 'CA',
    PostalCode: 95020,
    Country: 'US',
    Phone: '408/847-8000',
    Fax: '408/847-8888',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US017',
    Name: 'Beth\'s Pad',
    Lines: '25 Main Street',
    City: 'Sunnyvale',
    State: 'CA',
    PostalCode: 94087,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US018',
    Name: 'Ariba Pad',
    Lines: '9966 Mercury Liquid Center',
    City: 'Sunnyvale',
    State: 'CA',
    PostalCode: 94086,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US019',
    Name: 'Ariba Warehouse',
    Lines: '3400 Los Gatos Blvd.',
    City: 'Los Gatos',
    State: 'CA',
    PostalCode: 95032,
    Country: 'US',
    Phone: '408/395-3800',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US020',
    Name: 'Timbuktu',
    Lines: '25 Serengetti Lane',
    City: 'San Jose',
    State: 'CA',
    PostalCode: 95123,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US021',
    Name: 'Atlanta',
    Lines: '123 atlanta Street',
    City: 'Atlanta',
    State: 'GA',
    PostalCode: 30301,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'US022',
    Name: 'Chicago',
    Lines: '123 chicago Street',
    City: 'chicago',
    State: 'IL',
    PostalCode: 61006,
    Country: 'US',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'FRA01',
    Name: 'Paris',
    Lines: 'Immeuble "Monte Carlo"13 rue Mayer',
    City: 'Paris',
    State: '',
    PostalCode: 58982,
    Country: 'FR',
    Phone: '47-62-20-14',
    Fax: '47-62-13-11',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'FRA02',
    Name: 'Paris Siege',
    Lines: '11 rue des bouvets',
    City: 'Nanterre',
    State: '',
    PostalCode: 92100,
    Country: 'FR',
    Phone: '47 62 24 00',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'FRA03',
    Name: 'Strasbourg',
    Lines: '15, rue des accacias Z I du vieux bois',
    City: 'Strasbourg',
    State: '',
    PostalCode: 67150,
    Country: 'FR',
    Phone: '33 47 24 12 18',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'FRA04',
    Name: 'Nanterre',
    Lines: '5, rue des bouvets',
    City: 'NANTERRE',
    State: '',
    PostalCode: 92000,
    Country: 'FR',
    Phone: '33 47 58 69 70',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'GB001',
    Name: 'London',
    Lines: '14 Gateshead Green',
    City: 'London',
    State: '',
    PostalCode: 'SW1',
    Country: 'GB',
    Phone: '0171-9746621',
    Fax: '0171-9745305',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'GB002',
    Name: 'Manchester',
    Lines: '1524 Upchurch Lane Newcastle Road',
    City: 'Manchester',
    State: '',
    PostalCode: 'MN',
    Country: 'GB',
    Phone: '61-499-2323',
    Fax: '61-499-5678',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'GB003',
    Name: 'Guildford',
    Lines: '1525 Upchurch Lane',
    City: 'Guildford',
    State: '',
    PostalCode: 'GU19 3TT',
    Country: 'GB',
    Phone: '01209 673401',
    Fax: '01209 673411',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'GB004',
    Name: 'Birmingham',
    Lines: '1 Stout St',
    City: 'Birmingham',
    State: '',
    PostalCode: '',
    Country: 'GB',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'GB005',
    Name: 'Manchester Stores',
    Lines: '1525 Upchurch Lane Newcastle Road',
    City: 'Manchester',
    State: '',
    PostalCode: 'MN',
    Country: 'GB',
    Phone: '61-999-2323',
    Fax: '61-999-5678',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'GB006',
    Name: 'Northern',
    Lines: 'Receiving Location Nothern Warehouse',
    City: '',
    State: '',
    PostalCode: '',
    Country: 'GB',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'GB007',
    Name: 'Amsterdam',
    Lines: '5500 Marlow On The Thames',
    City: 'Egham',
    State: '',
    PostalCode: '098766',
    Country: 'GB',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'DE001',
    Name: 'Mosach',
    Lines: 'Hanauer Str. 87',
    City: 'Muenchen',
    State: '',
    PostalCode: 80993,
    Country: 'DE',
    Phone: '089-',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'IT001',
    Name: 'Rome',
    Lines: 'v.le G.Cesare 54',
    City: 'Roma',
    State: '',
    PostalCode: '00165',
    Country: 'IT',
    Phone: '06-8763245',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'IT002',
    Name: 'Roma uff. vendite',
    Lines: 'V. C.Pavese 44',
    City: 'Roma',
    State: '',
    PostalCode: '00186',
    Country: 'IT',
    Phone: '06-50264453',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN01',
    Name: 'Mississauga',
    Lines: '100 Matheson Blvd. West Suite 100',
    City: 'Mississauga',
    State: 'TORONTO',
    PostalCode: 'L5R 3P4',
    Country: 'CA',
    Phone: '905-890-0800',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN02',
    Name: 'Ottawa',
    Lines: '50 O\'Connor Street Suite 1500',
    City: 'Ottawa',
    State: 'OTTOWA HULL',
    PostalCode: 'K1P 6L9',
    Country: 'CA',
    Phone: '613-238-2381',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN03',
    Name: 'Montreal',
    Lines: '600 Boul. de Maisonneuve ouest Bureau 1010',
    City: 'Montreal',
    State: 'MONTREAL',
    PostalCode: 'H3A 3J2',
    Country: 'CA',
    Phone: '514-843-6762',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN04',
    Name: 'Quebec City',
    Lines: '3107 Avenue des Hotels Bureau 5',
    City: 'Sainte-Foy',
    State: 'QUEBEC',
    PostalCode: 'G1W 4W5',
    Country: 'CA',
    Phone: '418-652-1363',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN05',
    Name: 'Hull',
    Lines: '975 Boul. St. Joseph Bureau 228',
    City: 'Hull',
    State: 'OTTOWA HULL',
    PostalCode: 'J8Z 1W8',
    Country: 'CA',
    Phone: '819-772-2606',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN06',
    Name: 'Calgary',
    Lines: 'Moonlite Circle Suite 1720 112 - 4th Avenue S.W.',
    City: 'Moosehead',
    State: 'CALGARY',
    PostalCode: 'T2P 0H3',
    Country: 'CA',
    Phone: '403-265-2622',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN07',
    Name: 'Edmonton',
    Lines: 'Canada Trust Tower Sute 3101 10104 - 103 Avenue',
    City: 'Edmonton',
    State: 'EDMONTON',
    PostalCode: 'T5J 0H8',
    Country: 'CA',
    Phone: '403-421-4511',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN08',
    Name: 'Vancouver',
    Lines: '1055 West Hastings Street Suite 1500',
    City: 'Vancouver',
    State: 'VANCOUVER',
    PostalCode: 'V6E 2E9',
    Country: 'CA',
    Phone: '604-682-8965',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN09',
    Name: 'Regina',
    Lines: 'Heritage Business Centre 301 East Wing 2201 - 11th Avenue',
    City: 'Regina',
    State: 'REGINA',
    PostalCode: 'S4P 0J8',
    Country: 'CA',
    Phone: '306-359-6677',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN10',
    Name: 'Victoria',
    Lines: '1290 Broad Street Suite 201',
    City: 'Victoria',
    State: 'VICTORIA',
    PostalCode: 'V8W 2A5',
    Country: 'CA',
    Phone: '604-360-2634',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN11',
    Name: 'Winnipeg',
    Lines: '201 Portage Avenue at Main Street Suite 3106',
    City: 'Winnipeg',
    State: 'WINNEPEG',
    PostalCode: 'R3B 0X1',
    Country: 'CA',
    Phone: '204-925-4200',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'CAN12',
    Name: 'Manulife',
    Lines: 'P.O. Box 6000',
    City: 'Waterloo',
    State: 'KITCHENER',
    PostalCode: 'K1G 2P4',
    Country: 'CA',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'MX001',
    Name: 'Mexico',
    Lines: '123 Calle Principal',
    City: 'Mexico City',
    State: 'MX',
    PostalCode: 123456,
    Country: 'MX',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'JPN01',
    Name: 'Nihon Ariba K.K',
    Lines: 'Akasaka Twin Tower East 11F 2-17-22 Akasaka',
    City: 'Minato-ku',
    State: 'Tokyo',
    PostalCode: '107-0052',
    Country: 'JP',
    Phone: '81-3 6230-0700',
    Fax: '81-3 6230-0770',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'JPN02',
    Name: 'Japan',
    Lines: '5-10-999 Sotobori-dori',
    City: 'Tokyo',
    State: 'JP',
    PostalCode: 123456,
    Country: 'JP',
    Phone: '',
    Fax: '',
    Email: '',
    URL: ''
  },
  {
    UniqueName: 'FI001',
    Name: 'Espoo',
    Lines: 'Karaportti 15',
    City: 'ESPOO',
    State: '',
    PostalCode: '02610',
    Country: 'FI',
    Phone: '458 2182 06367',
    Fax: '458 2289 66749',
    Email: '',
    URL: ''
  }
];
