name: Nx Cloud Agents

on:
    workflow_call:
        secrets:
            NX_CLOUD_ACCESS_TOKEN:
                required: false
            NX_CLOUD_AUTH_TOKEN:
                required: false
        inputs:
            number-of-agents:
                required: true
                type: number

env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_BRANCH: ${{ github.event.number || github.ref_name }}
    NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
    set-agents:
        runs-on: ${{ inputs.runs-on }}
        name: Init
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - id: set-matrix
              shell: bash
              # Turn the number-of-agents input into a JSON structure which is compatible with a Github job matrix strategy
              run: |
                  AGENTS_JSON_ARRAY=$(node -e "console.log(JSON.stringify(Array.from(new Array(${{ inputs.number-of-agents }})).map((_, i) => i + 1)));")
                  echo $AGENTS_JSON_ARRAY
                  echo "::set-output name=matrix::$AGENTS_JSON_ARRAY"

    Run:
        needs: set-agents
        runs-on: ${{ inputs.runs-on }}
        name: Agent ${{ matrix.agent }}
        strategy:
            matrix:
                agent:
                    - ${{fromJson(needs.set-agents.outputs.matrix)}}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/nodejs
              with:
                  node-version: 14.20.0
            - run: |
                  export DISPLAY=:99
                  sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
            - name: Start Nx Agent ${{ matrix.agent }}
              run: npx nx-cloud start-agent
              env:
                  NX_AGENT_NAME: ${{matrix.agent}}
                  name: Nx Cloud Agents
